# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
# https://github.com/home-assistant/docker-base/pkgs/container/aarch64-base
build_from:
  amd64: "ghcr.io/home-assistant/amd64-base-ubuntu:20.04"
  # aarch64: "ghcr.io/home-assistant/aarch64-base-ubuntu:20.04"

labels:
  org.opencontainers.image.title: "underknowledge.puppeteer-homeassistant-addon"
  org.opencontainers.image.description: "A Pupeteer setup to bring an image of a Home Assistant dashboard to Kindle!"
  org.opencontainers.image.source: "https://github.com/Underknowledge/underknowledge.puppeteer-homeassistant-addon"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
