# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Containerized Pupeteer setup
version: "0.0.6"
slug: puppeteer-homeassistant
description: puppeteer-homeassistant add-on
url: "https://github.com/Underknowledge/underknowledge.puppeteer-homeassistant-addon/tree/main/puppeteer-homeassistant"
arch:
  - aarch64
  - amd64
init: false
map:
  - config:rw
  - ssl # maybe as an deploy key? 
options:
  message: "Hello world..."
  kindle_ip: "10.0.0.3"
  kindle_password: "CleartextPasswordsAreTerrible!!!"
  homeassistant_login: kindle
  homeassistant_password: kindle
  homeassistant_url: http://10.0.0.2:8123/vr-welcome/kindle?kiosk
  desiredWidth: "758"
  desiredHeight: "1024"
  ScaleFactor: "1"
schema:
  message: "str"
  kindle_ip: "str"
  kindle_password: "str"
  homeassistant_login: "str"
  homeassistant_password: "str"
  homeassistant_url: "str"
# to be implemented 
  desiredWidth: "str"
  desiredHeight: "str"
  ScaleFactor: "str"
#image: "ghcr.io/Underknowledge/{arch}-puppeteer-homeassistant"


# SLEEP=1m
# READING_DURATION=2h